---
title: "data_analysis"
author: 'Author: Yelu He'
date: "2023-08-17"
output: html_document
---

# Library
```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
################################################################################
options(scipen = 6)         # Display digits, not the scientific version
options(digits = 4)         # Number of significant digits used to display numbers
options(digits.secs = 6)    # Use milliseconds in Date/Time data types
options(warning = FALSE)    # Don't show warnings

## Default repository
local({r <- getOption("repos")
r["CRAN"] <- "http://cran.r-project.org" 
options(repos=r)
})

test_pkg <- function(x)
{
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}

test_pkg("sf")
test_pkg("tidyverse")
test_pkg("dplyr")
test_pkg("sp")
test_pkg("ggplot2")
test_pkg("readxl")
test_pkg("proj4")
test_pkg("terra")
# test_pkg("leaflet")
# test_pkg("spatstat")
# test_pkg("rgdal")
# test_pkg("osmdata")
# test_pkg("osmplotr")
# 
# test_pkg("spatialEco")
# test_pkg("sfnetworks")
# 
# test_pkg("tidygraph")
# test_pkg("lwgeom")
# test_pkg("tmap")
# test_pkg("spdep")
# test_pkg("ows4R")
# test_pkg("ggforce")
# test_pkg("dbscan")
# test_pkg("spdep")
# test_pkg("units")
# test_pkg("caret")
# test_pkg("caTools")
# test_pkg("Matrix")


dataFolder   <- here::here("D:/MT_D/data/")
# RFolder      <- here::here("D:/MT_D/Rscript")
# figureFolder <- here::here("D:/MT_D/figs")

```

# Data 
## Data cleaning
```{r data, echo = TRUE, warning = FALSE, message = FALSE}
# Import data
data_raw <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx")
excel_sheets("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx")

data_s1 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Allgemeine Angaben")
colnames(data_s1)[5:12] <- c("UnfalltypGruppenumber", "UnfalltypGroupename", 
                             "Unfalltypnumber", "Unfalltypname",
                             "G", "SV", "LV", "Sachschaden")
colnames(data_s1)[15:16] <- c("KoordE", "KoordN")
data_s1 <- subset(data_s1, select = -c(Bemerkung))
data_s1 <- subset(data_s1, select = -c(Nr.))
# colnames(data_s1)

data_s2 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Infrastruktur")
data_s2 <- subset(data_s2, select = -c(Bemerkung)) 
data_s2 <- subset(data_s2, select = -c(Nr.))
colnames(data_s2)[3] <- "Innerausserorts"
colnames(data_s2)[6] <- "Hochstgeschwindigkeit"
colnames(data_s2)[7] <- "Strassenbeleuchtung"
# colnames(data_s2)


data_s3 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Bedingungen")
data_s3 <- subset(data_s3, select = -c(Bemerkung))
data_s3 <- subset(data_s3, select = -c(Nr.))
colnames(data_s3)[3] <- "Lichtverhaltnis"
# colnames(data_s3)

data_s4 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Objekte und Personen")
data_s4 <- subset(data_s4, select = -c(Bemerkung))
data_s4 <- subset(data_s4, select = -c(Nr.))
colnames(data_s4)[4] <- "Blutalkoholkonzent"
colnames(data_s4)[5] <- "Atemalkoholkonzent"
# colnames(data_s4)


data_s5 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Beteiligungen 1")
data_s5 <- subset(data_s5, select = -c(Bemerkung))
data_s5 <- subset(data_s5, select = -c(Nr.))
colnames(data_s5)[2:11] <- c("Kinderunfall",
                            "KinderunfallaufdemSchulweg",
                            "Seniorenunfall",
                            "AnzahlKinder",
                            "AnzahlKinderaufdemSchulweg",
                            "AnzahlSenioren",
                            "AnzahlFussgangeroderFag",
                            "AnzahlFahrrader",
                            "AnzahlFahrradermitelektrTretunterstutzungbis25",
                            "AnzahlFahrradermitelektrTretunterstutzungbis45")
# colnames(data_s5)

data_s6 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Beteiligungen 2")
data_s6 <- subset(data_s6, select = -c(Bemerkung))
data_s6 <- subset(data_s6, select = -c(Nr.))
colnames(data_s6)[2:4] <- c("MotorFahrrader", 
                            "Kleinmotorraderbis50undmax4",
                            "Motorrader")
colnames(data_s6)[7:9] <- c("Personenwagen",
                            "TransportmitteldesOV",
                            "AndereFahrzeuge")
colnames(data_s6)


data_s7 <- read_excel("D:/MT_D/data/E_Trottis_Unfallbericht_2019_2022_note.xlsx", 
                      sheet = "Unfälle nach Unfalltyp")
# Merge all the sheets
m1 <- merge(data_s1, data_s2, 
            by.x = "Unfall-Nr.",
            by.y = "Unfall-Nr.")

m2 <- merge(m1, data_s3,
            by.x = "Unfall-Nr.",
            by.y = "Unfall-Nr.")
m3 <- merge(m2, data_s4,
            by.x = "Unfall-Nr.",
            by.y = "Unfall-Nr.")
m4 <- merge(m3, data_s5,
            by.x = "Unfall-Nr.",
            by.y = "Unfall-Nr.")
m5 <- merge(m4, data_s6, 
            by.x = "Unfall-Nr.",
            by.y = "Unfall-Nr.")

df <- m5
str(df)
colnames(df)[1] <- "UnfallNr"
colnames(df)[26] <- "ObjektNr"

colnames(df)


```

## Data statistical analysis
### Time
```{r time, echo=TRUE, message=FALSE, warning=FALSE}
df_escooter <- df
duplicated_col <- duplicated(t(df_escooter))
colnames(df_escooter[duplicated_col])
df_escooter <- df_escooter[!duplicated_col]
colnames(df_escooter)

df_escooter$month <- format(as.Date(df_escooter$Datum), "%m")
df_escooter$year <- format(as.Date(df_escooter$Datum), "%Y")
df_escooter$day <- format(as.Date(df_escooter$Datum), "%d")

unique(df_escooter$year)
str(df_escooter$year)
df_escooter$year <- as.numeric(df_escooter$year)

# Year
sta_year <- df_escooter %>% count(year)
ggplot(data = sta_year, 
       aes(x = year, y = n, group = 1)) +
  geom_line() +
  geom_point()

# Month
sta_month <- df_escooter %>% count(month)
ggplot(data = sta_month, 
       aes(x = month, y = n, group = 1)) +
  geom_line() +
  geom_point()

# Month_year
sta_month_year <- df_escooter %>% count(month,year)
sta_month_year$year <- factor(sta_month_year$year)
ggplot(data = sta_month_year, 
       aes(x = month, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_month_year, aes(x = month, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

# Day
sta_day <- df_escooter %>% count(day)
ggplot(data = sta_day, 
       aes(x = day, y = n, group = 1)) +
  geom_line() +
  geom_point()

# Time
df_escooter$month <- format(as.Date(df_escooter$Datum), "%m")
df_escooter$time <- substr(df_escooter$Zeit, 1, 2)
df_escooter$time <- as.numeric(df_escooter$time)
# unique(df_escooter$time)
df_escooter$Zeit
unfall_time <- df_escooter %>% select('Zeit', 'time', 'year')
unfall_time
sta_time <- unfall_time %>% count(time)
sum(sta_time$n)
ggplot(data = sta_time, 
       aes(x = time, y = n, group = 1)) +
  geom_line() +
  geom_point()
sta_time
# time_year
sta_time_year <- unfall_time %>% count(time,year)
sta_time_year$year <- factor(sta_time_year$year)
ggplot(data = sta_time_year, 
       aes(x = time, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_time_year, aes(x = time, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")


# Day number of each week
df_escooter$wd <- wday(df_escooter$Datum, week_start = 1)
# Week day number starts from Monday, Monday is 1. 
sta_wd <- df_escooter %>% count(wd)
sta_wd
ggplot(data = sta_wd, 
       aes(x = wd, y = n, group = 1)) +
  geom_line() +
  geom_point()
# Day number of each week - year
sta_wd_year <- df_escooter %>% count(wd, year)
sta_wd_year$year <- factor(sta_wd_year$year)
ggplot(data = sta_wd_year, 
       aes(x = wd, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_wd_year, aes(x = wd, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")


```

### Impact
```{r impact, echo = TRUE, warning = FALSE, message = FALSE}


sta_G_year <- df_escooter %>% count(G,year)
sta_G_year$year <- factor(sta_G_year$year)
ggplot(data = sta_G_year, 
       aes(x = G, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_G_year, aes(x = G, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

sta_SV_year <- df_escooter %>% count(SV,year)
sta_SV_year$year <- factor(sta_SV_year$year)
ggplot(data = sta_SV_year, 
       aes(x = SV, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_SV_year, aes(x = SV, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

sta_LV_year <- df_escooter %>% count(LV,year)
sta_LV_year$year <- factor(sta_LV_year$year)
ggplot(data = sta_LV_year, 
       aes(x = LV, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_LV_year, aes(x = LV, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

# sta_sachschaden_year <- df_escooter %>% count(Sachschaden,year)
# sta_sachschaden_year$year <- factor(sta_sachschaden_year$year)
# ggplot(data = sta_sachschaden_year, 
#        aes(x = Sachschaden, y = n, group = year)) +
#   geom_line(aes(colour = year)) +
#   geom_point()
# 
# ggplot(data = sta_sachschaden_year, aes(x = Sachschaden, y = n, fill = year)) + 
#     geom_bar(position="stack", stat="identity") +
#     scale_fill_brewer(palette = "Set2")
# 

hist(df_escooter$Sachschaden)

```

### Location
```{r location, echo = TRUE, warning = FALSE, message = FALSE}
sta_Unfallstelle_year <- df_escooter %>% count(Unfallstelle,year)
sta_Unfallstelle_year$year <- factor(sta_Unfallstelle_year$year)
ggplot(data = sta_Unfallstelle_year, 
       aes(x = Unfallstelle, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_Unfallstelle_year, aes(x = Unfallstelle, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

sta_Innerausserorts_year <- df_escooter %>% count(Innerausserorts,year)
sta_Innerausserorts_year$year <- factor(sta_Innerausserorts_year$year)
ggplot(data = sta_Innerausserorts_year, 
       aes(x = Innerausserorts, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_Innerausserorts_year, aes(x = Innerausserorts, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

sta_Strassenart_year <- df_escooter %>% count(Strassenart,year)
sta_Strassenart_year$year <- factor(sta_Strassenart_year$year)
ggplot(data = sta_Strassenart_year, 
       aes(x = Strassenart, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_Strassenart_year, aes(x = Strassenart, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")


sta_Hochstgeschwindigkeit_year <- df_escooter %>% count(Hochstgeschwindigkeit,year)
sta_Hochstgeschwindigkeit_year$year <- factor(sta_Hochstgeschwindigkeit_year$year)
ggplot(data = sta_Hochstgeschwindigkeit_year, 
       aes(x = Hochstgeschwindigkeit, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_Hochstgeschwindigkeit_year, aes(x = Hochstgeschwindigkeit, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")



```


### Traffic
```{r traffic, echo = TRUE, warning = FALSE, message = FALSE}
sta_Strassenbeleuchtung_year <- df_escooter %>% count(Strassenbeleuchtung,year)
sta_Strassenbeleuchtung_year$year <- factor(sta_Strassenbeleuchtung_year$year)
ggplot(data = sta_Strassenbeleuchtung_year, 
       aes(x = Strassenbeleuchtung, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_Strassenbeleuchtung_year, aes(x = Strassenbeleuchtung, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")


sta_Verkehrsaufkommen_year <- df_escooter %>% count(Verkehrsaufkommen,year)
sta_Verkehrsaufkommen_year$year <- factor(sta_Verkehrsaufkommen_year$year)
ggplot(data = sta_Verkehrsaufkommen_year, 
       aes(x = Verkehrsaufkommen, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Verkehrsaufkommen_year, aes(x = Verkehrsaufkommen, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")


sta_Strassenart_year <- df_escooter %>% count(Strassenart,year)
sta_Strassenart_year$year <- factor(sta_Strassenart_year$year)
ggplot(data = sta_Strassenart_year, 
       aes(x = Strassenart, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()

ggplot(data = sta_Strassenart_year, aes(x = Strassenart, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")



```

### Conditions
```{r condition, echo = TRUE, warning = FALSE, message = FALSE}
# Road condition
sta_Strassenzustand_year <- df_escooter %>% count(Strassenzustand,year)
sta_Strassenzustand_year$year <- factor(sta_Strassenzustand_year$year)
ggplot(data = sta_Strassenzustand_year, 
       aes(x = Strassenzustand, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Strassenzustand_year, aes(x = Strassenzustand, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

# Weather
sta_Witterung_year <- df_escooter %>% count(Witterung,year)
sta_Witterung_year$year <- factor(sta_Witterung_year$year)
ggplot(data = sta_Witterung_year, 
       aes(x = Witterung, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Witterung_year, aes(x = Witterung, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")


# Light
sta_Lichtverhaltnis_year <- df_escooter %>% count(Lichtverhaltnis,year)
sta_Lichtverhaltnis_year$year <- factor(sta_Lichtverhaltnis_year$year)
ggplot(data = sta_Lichtverhaltnis_year, 
       aes(x = Lichtverhaltnis, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Lichtverhaltnis_year, aes(x = Lichtverhaltnis, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")



```


### Object and person
```{r op, echo = TRUE, warning = FALSE, message = FALSE}
# Vehicle type
sta_Fahrzeugart_year <- df_escooter %>% count(Fahrzeugart,year)
sta_Fahrzeugart_year$year <- factor(sta_Fahrzeugart_year$year)
ggplot(data = sta_Fahrzeugart_year, 
       aes(x = Fahrzeugart, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Fahrzeugart_year, aes(x = Fahrzeugart, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

hist(df_escooter$Blutalkoholkonzent)
hist(df_escooter$Atemalkoholkonzent)


# person type
sta_Personenart_year <- df_escooter %>% count(Personenart,year)
sta_Personenart_year$year <- factor(sta_Personenart_year$year)
ggplot(data = sta_Personenart_year, 
       aes(x = Personenart, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Personenart_year, aes(x = Personenart, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

# Consequences
sta_Unfallfolgen_year <- df_escooter %>% count(Unfallfolgen,year)
sta_Unfallfolgen_year$year <- factor(sta_Unfallfolgen_year$year)
ggplot(data = sta_Unfallfolgen_year, 
       aes(x = Unfallfolgen, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Unfallfolgen_year, aes(x = Unfallfolgen, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

# Impact
sta_Anprall_year <- df_escooter %>% count(Anprall,year)
sta_Anprall_year$year <- factor(sta_Anprall_year$year)
ggplot(data = sta_Anprall_year, 
       aes(x = Anprall, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Anprall_year, aes(x = Anprall, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

# Age
sta_Alter_year <- df_escooter %>% count(Alter,year)
sta_Alter_year$year <- factor(sta_Alter_year$year)
ggplot(data = sta_Alter_year, 
       aes(x = Alter, y = n, group = year)) +
  geom_line(aes(colour = year)) +
  geom_point()
ggplot(data = sta_Alter_year, aes(x = Alter, y = n, fill = year)) + 
    geom_bar(position="stack", stat="identity") +
    scale_fill_brewer(palette = "Set2")

```


#### Stop work here to be continued
### Accident type

```{r info, echo = TRUE, warning = FALSE, message = FALSE}

sta_unfalltypgruppe <- df_escooter %>% count(UnfalltypGruppenumber)

ggplot(data = sta_unfalltypgruppe, 
       aes(x = UnfalltypGruppe, y = n, group = 1)) +
  geom_line() +
  geom_point()

```

```{r info2, echo = TRUE, warning = FALSE, message = FALSE}
unfalltyp_table <- df_escooter %>% select('Unfalltyp', 'UnfalltypName')
unfalltyp_table <- unique(unfalltyp_table)

sta_unfalltyp <- df_escooter %>% count(Unfalltyp)
sta_unfalltyp <- merge(sta_unfalltyp, unfalltyp_table, by.x = 'Unfalltyp', by.y = 'Unfalltyp')

sta_unfalltyp[order(sta_unfalltyp$Unfalltyp),]
sta_type <- sta_unfalltyp[order(sta_unfalltyp$n, decreasing = TRUE),]

sta_unfalltyp$Unfalltyp <- as.numeric(sta_unfalltyp$Unfalltyp)

ut0 <- filter(sta_unfalltyp, (Unfalltyp >= 1) & (Unfalltyp <= 9))
ut0

ut1 <- filter(sta_unfalltyp, (Unfalltyp >= 10) & (Unfalltyp <= 19))
ut1

ut2 <- filter(sta_unfalltyp, (Unfalltyp >= 20) & (Unfalltyp <= 29))
ut2

ut3 <- filter(sta_unfalltyp, (Unfalltyp >= 30) & (Unfalltyp <= 39))
ut3

ut4 <- filter(sta_unfalltyp, (Unfalltyp >= 40) & (Unfalltyp <= 49))
ut4

ut5 <- filter(sta_unfalltyp, (Unfalltyp >= 50) & (Unfalltyp <= 59))
ut5

ut6 <- filter(sta_unfalltyp, (Unfalltyp >= 60) & (Unfalltyp <= 69))
ut6

ut7 <- filter(sta_unfalltyp, (Unfalltyp >= 70) & (Unfalltyp <= 79))
ut7

ut8 <- filter(sta_unfalltyp, (Unfalltyp >= 80) & (Unfalltyp <= 89))
ut8

ut9 <- filter(sta_unfalltyp, (Unfalltyp >= 90) & (Unfalltyp <= 99))
ut9

sta_unfalltyp
ggplot(data = sta_unfalltyp, 
       aes(x = Unfalltyp, y = n, group = 1)) +
  geom_line() +
  geom_point()

sta_type[1:10,]
sum(sta_unfalltyp$n)

```





## Map
```{r map, echo = TRUE, warning = FALSE, message = FALSE}
zurich_map <- st_read(file.path(dataFolder, "stadtkreis/stadtkreis/Stadtkreis.shp"))
zurich_map <- st_transform(zurich_map, epsg = 2056)

mapraw <- st_as_sf(df_escooter, coords = c("KoordE", "KoordN"), crs = 2056, remove = FALSE)

ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = mapraw, alpha = 0.3, show.legend = "point") +
  theme_void()

ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = mapraw, aes(color = year), alpha = 0.3, show.legend = "point") +
  theme_void()


df_escooter_19 <- mapraw[mapraw$year == '2019',]
df_escooter_20 <- mapraw[mapraw$year == '2020',]
df_escooter_21 <- mapraw[mapraw$year == '2021',]
df_escooter_22 <- mapraw[mapraw$year == '2022',]
map19 <- 
  ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = df_escooter_19, alpha = 0.3, show.legend = "point") +
  theme_void()
map19
# ggsave("D:/MT_D/figs/19.png", plot = map19)

map20 <- 
  ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = df_escooter_20, alpha = 0.3, show.legend = "point") +
  theme_void()
map20
# ggsave("D:/MT_D/figs/20.png", plot = map20)

map21 <- 
  ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = df_escooter_21, alpha = 0.3, show.legend = "point") +
  theme_void()
map21
# ggsave("D:/MT_D/figs/21.png", plot = map21)

map22 <- 
  ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = df_escooter_22, alpha = 0.3, show.legend = "point") +
  theme_void()
map22
# ggsave("D:/MT_D/figs/22.png", plot = map22)


```

### Crash locations
```{r locat, echo = TRUE, warning = FALSE, message = FALSE}
# For google street view images
lo <- subset(data_s1, select = c('KoordE','KoordN'))
lo <- st_as_sf(lo, 
               coords = c("KoordE",
                          "KoordN"), 
               crs = 2056, 
               remove = TRUE)
lo_2 <- st_transform(lo, 
                     "+proj=longlat +ellps=WGS84 +datum=WGS84")
location_lonlat <- st_coordinates(lo_2)


ggplot() + 
  geom_sf(data = zurich_map, fill = "white", 
          color = "black", size = 0.1) +
  geom_sf(data = lo_2, alpha = 0.3, show.legend = "point") +
  theme_void()


lo_0 <- st_transform(lo, "+proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs +type=crs")

library(sf)
library(sp)
library(rgdal)
lo_0 <- spTransform(lo, CRS("+proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs +type=crs"))


library(tidyverse)
library(tidyr)
lo %>% tidyr::extract(geometry,
                     c('lat', 'lon'),
                     '\\((.*), (.*)\\)', 
                     convert = TRUE)

## Convert CH y/x to WGS lat
CH.to.WGS.lat <- function (y, x){

	## Converts military to civil and  to unit = 1000km
	## Auxiliary values (% Bern)
	y_aux <- (y - 600000)/1000000
	x_aux <- (x - 200000)/1000000
  
	## Process lat
	lat <- {16.9023892 +
	3.238272 * x_aux -
	0.270978 * (y_aux^2) -
	0.002528 * (x_aux^2) -
	0.0447   * (y_aux^2) * x_aux -
	0.0140   * (x_aux^3)}
    
	## Unit 10000" to 1 " and converts seconds to degrees (dec)
	lat <- lat * 100/36
  
  	return(lat)  
}

## Convert CH y/x to WGS long
CH.to.WGS.lng <- function (y, x){

	## Converts military to civil and  to unit = 1000km
	## Auxiliary values (% Bern)
	y_aux <- (y - 600000)/1000000
	x_aux <- (x - 200000)/1000000
  
	## Process long
	lng <- {2.6779094 +
	4.728982 * y_aux +
	0.791484 * y_aux * x_aux +
	0.1306   * y_aux * (x_aux^2) -
	0.0436   * (y_aux^3)}
     
	## Unit 10000" to 1 " and converts seconds to degrees (dec)
  	lng <- lng * 100/36

	return(lng)
}

lo_1 <- lo
lo_1$lon <- CH.to.WGS.lng(lo$KoordN,
                          lo$KoordE)
lo_1$lat <- CH.to.WGS.lat(lo$KoordN,
                          lo$KoordE)



```

```{r info3, echo = TRUE, warning = FALSE, message = FALSE}
unique(df_escooter$Hauptursache)
sta_cause <- df_escooter %>% count(Hauptursache)
ggplot(data = sta_cause, 
       aes(x = Hauptursache, y = n, group = 1)) +
  geom_line() +
  geom_point()
sta_cause[order(sta_cause$n, decreasing = TRUE),]


df_escooter$Unfalltyp <- as.numeric(df_escooter$Unfalltyp)
ut0_1 <- filter(df_escooter, Unfalltyp == 1)
ut0_1$Unfalltyp
length(ut0_1$Unfalltyp)
sta_uf01_cause <- ut0_1%>% count(Hauptursache)
sta_uf01_cause[order(sta_uf01_cause$n, decreasing = TRUE),]

sta_roadtype <- df_escooter %>% count(Strassenart)
sta_roadtype[order(sta_roadtype$n, decreasing = TRUE),]

colnames(df_escooter)[22] <- "maxspeed"
sta_maxspeed <- df_escooter %>% count(maxspeed)
sta_maxspeed[order(sta_maxspeed$n, decreasing = TRUE),]



```



```{r info4, echo = TRUE, warning = FALSE, message = FALSE}

# Divide weekday and weekend
df_escooter_weekday <- filter(df_escooter, (wd >= 1) & (wd <= 5))
df_escooter_weekend <- filter(df_escooter, (wd >= 6) & (wd <= 7))

sta_weekday_time <-  df_escooter_weekday%>% count(time)
ggplot(data = sta_weekday_time, 
       aes(x = time, y = n, group = 1)) +
  geom_line() +
  geom_point()

sta_weekend_time <-  df_escooter_weekend%>% count(time)
ggplot(data = sta_weekend_time, 
       aes(x = time, y = n, group = 1)) +
  geom_line() +
  geom_point()


```



```{r info5, echo = TRUE, warning = FALSE, message = FALSE}
severity <- df_escooter %>% select('G', 'SV', 'LV','Unfallfolgen')
severity_ <- df_escooter %>% select('G', 'SV', 'LV')
df_escooter <- df_escooter %>% mutate(severity =
                     case_when(G == 1 ~ "6", 
                               ((LV == 1) & (SV == 1)) ~ "5",
                               ((LV == 0) & (SV == 1)) ~ "4",
                               ((LV == 3) & (SV == 0)) ~ "3",
                               ((LV == 2) & (SV == 0)) ~ "2",
                               ((LV == 1) & (SV == 0)) ~ "1",
                               ((G == 0) & (SV == 0) & (LV == 0) ~ "0")
))
sta_severity <-  df_escooter%>% count(severity)
sta_severity
sev <- sta_severity$n
sev
sev <- c(46, 221, 22, 2, 53, 6)
sl <- c("nicht verletzt", "1 leicht verletzt","2 leicht verletzt","3 leicht verletzt","1 schwer verletzt","1 leicht verletzt + 1 schwer verletzt")
pie(sev, sl)

per<- round(100*sev/sum(sev), 1)

# Plot the chart.
pie(sev, labels = per,col = rainbow(length(sev)))
legend("bottomright", c("nicht verletzt", "1 leicht verletzt","2 leicht verletzt","3 leicht verletzt","1 schwer verletzt","1 leicht verletzt + 1 schwer verletzt"), cex = 0.55,
   fill = rainbow(length(sev)))

unique(df$Verkehrsaufkommen)

sta_v <- df_escooter %>% count(Verkehrsaufkommen)
sta_v


```


```{r info6, echo = TRUE, warning = FALSE, message = FALSE}
# #list1 <- dir(here::here("D:/MT_D/GSV"))
# 
# #list <- data.frame(list1)
# #write.csv(list, "list.csv")
# 
# list_null <- dir(here::here("D:/MT_D/GSV_filtered/null"))
# list_null <- data.frame(list_null)
# # write.csv(list_null, "list_null.csv")
# 
# list_sky <- dir(here::here("D:/MT_D/GSV_filtered/sky"))
# list_sky <- data.frame(list_sky)
# #write.csv(list, "list.csv")
# 
# list_indoor <- dir(here::here("D:/MT_D/GSV_filtered/indoor"))
# list_indoor <- data.frame(list_indoor)
# 
# list_roof <- dir(here::here("D:/MT_D/GSV_filtered/roof"))
# list_roof <- data.frame(list_roof)
# 
# 
# 
# install.packages("qpcR")                            # Install qpcR package
# library("qpcR")                                     # Load qpcR package
# 
# data_cbind <- qpcR:::cbind.na(list_null, list_sky)           # Bind as columns
# data_cbind <- qpcR:::cbind.na(data_cbind, list_indoor)
# data_cbind <- qpcR:::cbind.na(data_cbind, list_roof)
# list_filter <- data_cbind
#  
# write.csv(list_filter, "list_filter.csv")
# 






```
